name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]

    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1
          PRISMA_HIDE_UPDATE_MESSAGE: 1
        run: npm ci

      - name: Generate Prisma client
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1
          PRISMA_HIDE_UPDATE_MESSAGE: 1
        run: npm run db:generate

      - name: Lint
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run lint

      - name: Type check
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run typecheck

      - name: Build
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1
          PRISMA_HIDE_UPDATE_MESSAGE: 1
          NEXTAUTH_URL: http://localhost:3000
        run: npm run build

